//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int sensor_id { get; set; }
        public int event_type { get; set; }
        public double value { get; set; }
    }
}
